openapi: 3.0.0
info:
  title: caribe api
  version: '1.0'
  contact:
    email: rubenrequena@gmail.com
    name: Ruben Requena
  description: API para las taquillas de escritorio del sistema CaribeApuesta
servers:
  - url: 'http://51.83.141.121:3000'
paths:
  /auth:
    post:
      summary: Autenticacion
      operationId: post-auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  activo:
                    type: boolean
                  jerarquia:
                    type: array
                    items:
                      type: string
                  moneda:
                    type: object
                    properties:
                      _id:
                        type: string
                      nombre:
                        type: string
                      siglas:
                        type: string
                  nombre:
                    type: string
                  usuario:
                    type: string
                  rol:
                    type: string
                  correo:
                    type: string
                  telefono:
                    type: string
                  permisos:
                    type: array
                    items:
                      type: integer
                  codigo:
                    type: string
                  token:
                    type: string
                  grupoPago:
                    type: string
              examples:
                Ejemplo:
                  value:
                    _id: 5fac30a3d417f82b2ccbba87
                    activo: true
                    jerarquia:
                      - 5fac0cb3f4131413ec042696
                      - 5fac30a3d417f82b2ccbba76
                    moneda:
                      _id: 5f3f9f72e8430007447ced9b
                      nombre: Bolivar
                      siglas: ves
                      principal: true
                      __v: 0
                    nombre: ONLINE 1
                    usuario: online1
                    clave: 81dc9bdb52d04dc20036dbd8313ed055
                    rol: online
                    correo: online1@gmail.com
                    telefono: '04149970167'
                    permisos:
                      - 1
                      - 10
                      - 11
                      - 20
                      - 21
                      - 22
                      - 23
                      - 30
                      - 31
                      - 40
                      - 41
                      - 50
                      - 51
                      - 52
                      - 60
                      - 61
                      - 70
                      - 71
                      - 72
                    codigo: 0-63-29
                    grupoPago: 5fac30a3d417f82b2ccbba80
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFjMzBhM2Q0MTdmODJiMmNjYmJhODciLCJub21icmUiOiJPTkxJTkUgMSIsInJvbCI6Im9ubGluZSIsImplcmFycXVpYSI6WyI1ZmFjMGNiM2Y0MTMxNDEzZWMwNDI2OTYiLCI1ZmFjMzBhM2Q0MTdmODJiMmNjYmJhNzYiXSwibW9uZWRhIjpbeyJfaWQiOiI1ZjNmOWY3MmU4NDMwMDA3NDQ3Y2VkOWIiLCJub21icmUiOiJCb2xpdmFyIiwic2lnbGFzIjoidmVzIiwicHJpbmNpcGFsIjp0cnVlLCJfX3YiOjB9XSwicGVybWlzb3MiOiI1ZmFjMGNiM2Y0MTMxNDEzZWMwNDI2OTciLCJpYXQiOjE2MDUxMjAyMTksImV4cCI6MTYwNTIwNjYxOX0.Q0SWiLnNQJUnXcttu5VAIIoK0kBJiDzUk4ecNE0SJZw
      description: punto de acceso para iniciar sesion
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                clave:
                  type: string
            examples:
              ejemplo:
                value:
                  usuario: pos1
                  clave: '1234'
        description: Solicitar inicio de sesion
      tags:
        - Sesion
  /sorteo/disponibles:
    get:
      summary: sorteos disponibles
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  sorteos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Sorteo'
                  operadora:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        sorteos:
                          type: array
                          items:
                            type: string
                        numeros:
                          type: string
                        nombre:
                          type: string
                        tipo:
                          type: string
                        paga:
                          type: number
                  numeros:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        nombre:
                          type: string
                        numeros:
                          type: array
                          items:
                            type: object
                            properties:
                              numero:
                                type: string
                              nombre:
                                type: string
              examples:
                example-1:
                  value:
                    sorteos:
                      - _id: string
                        descripcion: string
                        cierra: '2020-11-11T00:00:00Z'
                        operadora: string
                    operadora:
                      - _id: string
                        sorteos:
                          - string
                        numeros: string
                        nombre: string
                        tipo: string
                        paga: 0
                    numeros:
                      - _id: string
                        nombre: string
                        numeros:
                          - numero: string
                            nombre: string
          headers: {}
      operationId: get-sorteos-dispnibles
      description: Obtener listado de sorteos disponibles
    parameters: []
  /sorteo/conganador:
    get:
      summary: sorteos premiados
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      minLength: 1
                    descripcion:
                      type: string
                      minLength: 1
                    ganador:
                      type: string
                      minLength: 1
                  required:
                    - _id
                    - descripcion
                    - ganador
      operationId: get-sorteo-conganador
      description: Obtener el listado de sorteos premiados del dia
      parameters:
        - schema:
            type: string
          in: query
          name: operadora
          description: id de la operadora
          required: true
  /sorteo/buscar/fecha:
    get:
      summary: buscar sorteos
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sorteo'
      operationId: get-sorteo-buscar-fecha
      description: Buscar el listado de sorteos del dia solicitado
      parameters:
        - schema:
            type: string
            pattern: '\d{4}-\d{2}-\d{2}'
            minLength: 10
            maxLength: 10
            format: date
            example: '2020-11-11'
          in: query
          name: fecha
          required: true
          description: fecha en formato ISODate
        - schema:
            type: string
          in: query
          name: operadora
          description: id operadora
          required: true
  /ticket/venta:
    post:
      summary: vender
      operationId: post-ticket-venta
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ticket:
                    type: object
                    required:
                      - codigo
                      - serial
                      - creado
                      - monto
                      - anulado
                      - _id
                    properties:
                      codigo:
                        type: integer
                      serial:
                        type: string
                        minLength: 1
                      creado:
                        type: string
                        minLength: 1
                      monto:
                        type: number
                      anulado:
                        type: boolean
                      _id:
                        type: string
                        minLength: 1
                required:
                  - ticket
      description: Vender ticket
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  numero:
                    type: string
                    example: '10'
                    minLength: 1
                    maxLength: 3
                  sorteo:
                    type: string
                    description: id del sorteo
                  monto:
                    type: number
                    minimum: 1
                    example: 10000
                required:
                  - numero
                  - sorteo
                  - monto
        description: ''
      tags:
        - ticket
  /ticket/buscar/serial:
    get:
      summary: buscar ticket
      tags:
        - ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  _id:
                    type: string
                    minLength: 1
                  codigo:
                    type: number
                  serial:
                    type: string
                    minLength: 1
                  creado:
                    type: string
                    minLength: 1
                  monto:
                    type: number
                  anulado:
                    type: boolean
                  moneda:
                    type: string
                    minLength: 1
                  ventas:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        premio:
                          type: boolean
                        pagado:
                          type: boolean
                        numero:
                          type: string
                          minLength: 1
                        sorteo:
                          type: string
                          minLength: 1
                        monto:
                          type: number
                      required:
                        - _id
                        - premio
                        - pagado
                        - numero
                        - sorteo
                        - monto
                  sorteos:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        descripcion:
                          type: string
                          minLength: 1
                        operadora:
                          type: string
                          minLength: 1
                      required:
                        - _id
                        - descripcion
                        - operadora
                  operadoras:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        nombre:
                          type: string
                          minLength: 1
                      required:
                        - _id
                        - nombre
                required:
                  - _id
                  - codigo
                  - serial
                  - creado
                  - monto
                  - anulado
                  - moneda
                  - ventas
                  - sorteos
                  - operadoras
      operationId: get-ticket-buscar-serial
      description: buscar ticket por serial
      parameters:
        - schema:
            type: string
          in: query
          name: serial
          required: true
          description: Serial del ticket
  /ticket/buscar/ultimos:
    get:
      summary: buscar ultimos tickets
      tags:
        - ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    anulado:
                      type: boolean
                    codigo:
                      type: number
                    creado:
                      type: string
                      minLength: 1
                    moneda:
                      type: string
                      minLength: 1
                    monto:
                      type: number
                    serial:
                      type: string
                      minLength: 1
                    _id:
                      type: string
                      minLength: 1
                  required:
                    - anulado
                    - codigo
                    - creado
                    - moneda
                    - monto
                    - serial
                    - _id
              examples:
                ejemplo:
                  value:
                    - anulado: true
                      codigo: 0
                      creado: string
                      moneda: string
                      monto: 0
                      serial: string
                      _id: string
      operationId: get-ticket-buscar-ultimos
      description: Buscar ultimos tickets vendidos
      parameters:
        - schema:
            type: number
          in: query
          name: pagina
  /ticket/anular:
    post:
      summary: anular ticket
      operationId: post-ticket-anular
      responses:
        '200':
          description: OK
      description: Anular ticket
      tags:
        - ticket
components:
  schemas:
    Sorteo:
      title: Sorteo
      type: object
      properties:
        _id:
          type: string
        descripcion:
          type: string
        cierra:
          type: string
          format: date-time
          example: '2020-11-11T00:00:00Z'
        operadora:
          type: string
    Error:
      title: Error
      type: object
      properties:
        error:
          type: string
      description: Modelo para respuestas de error
  securitySchemes: {}
tags:
  - name: sorteos
  - name: ticket
  - name: Sesion
